New features
ScaleIT-Org/ionic-app-skeleton pull request #20
Opened 2018-06-14 11:53 UTC by kristkat

added a side menu as a page

2018-06-19 21:31 UTC, fridaypatrick requested changes
Please move the ion-menu and the hamburger button to the left as that is what the user usually expects.

2018-06-21 12:35 UTC, kristkat commented
Andrei wanted it to be on the right side. We had this discussion already and he didn't like when the hamburger button is before the app name. So we decided to place it with all icon buttons on the right side.

2018-06-23 13:48 UTC, derpatrick commented
Fine, then let's do it as @frostyandy2k wishes.

2018-06-23 13:48 UTC, fridaypatrick approved these changes

2018-06-26 10:59 UTC, merged